### PR TITLE
Include Yii as git submodule

### PR DESCRIPTION
**Pull request by DaSourcerer**
This PR takes Yii in as a [git submodule](http://git-scm.com/book/en/Git-Tools-Submodules) which will drastically decrease the size needed to host YiiBoilerplate on github and will also make it much easier to up- or downgrade Yii within a project. `git submodule init` should be executed after cloning.

### CODE REVIEW

**Comment by resurtm** [comment]
Maybe same should be done for ZF?

**Comment by DaSourcerer** [comment]
The same should be done for a lot of stuff. But Yii is most important and I've got little time right now :-/

**Comment by DaSourcerer** [comment]
Oh yes. Also: I couldn't find a reliable git repo for ZF1 yet.

**Comment by tonydspaniard** [comment]
I truly like submodules to update all dependencies but, after discussing with colleagues, we were concerned about those who download the zipball instead of cloning. 

We cannot assume that everybody knows "git" nor they have it installed on their computer, so I fear that if we do not implement another option (maybe a new command that we could run after runpostdeploy... not sure), people would find themselves hitting their heads against a wall .

I wish everybody works with "git", but I fear this is not happening nowadays yet.

**Comment by DaSourcerer** [comment]
> we were concerned about those who download the zipball instead of cloning. 

That is unfortunately a very sound reason for not taking this PR. It really looks like github ignores submodules entirely when serving repos as zip- or tarballs. Is there an alternative build service that could serve them?

**Comment by DaSourcerer** [comment]
I've just stumbled upon [this solution](http://marcelog.github.com/articles/ci_jenkins_hudson_continuous_integration_php_phing.html) which would require a working install of Jenkins and a Phing build.xml. Is this a lead worth pursuing for you?

**Comment by tonydspaniard** [comment]
Our good colleague sensorario from Yii network created Myii having Phing in mind and was also something that came to our thoughts but I believed that this will put an extra difficulty step to newbies. 

We need to come with a solution that comes out of the box, no need to pre-install or have requirements in order to run (apart from the obvious ones of course).

I have even thought to build a command that will automatically download and install the required libraries on the ./runpostdeploy command... What do you think about this possibility?

**Comment by githubjeka** [comment]
@tonydspaniard 
This will be a good solution. I adhere to the thought that all the libraries have been installed out of the box also.

**Comment by DaSourcerer** [comment]
@tonydspaniard: What I had in mind was something to automatically build a version of YiiBoilerplate that bundles all the git submodules into a zip- and/or tarball and uploads them to then [download section](https://github.com/clevertech/YiiBoilerplate/downloads). This would spare consumers to install and run phing. By the way: Phing can run some of git's commands itself. Unfortunately it doesn't seem like it has the powers to initialize submodules.

Another approach worth trying might be [git subtrees](https://help.github.com/articles/working-with-subtree-merge). Subtrees work a lot different than submodules, so it might be worth the try.

Something else: I'm afraid my PR isn't paying tribute to the altered paths to `yii.php`. As I wrote eralier, I've been in a hurry. Terribly sorry for that.

**Comment by tonydspaniard** [comment]
Git subtress definitely got my attention but I still need to investigate a bit and find out whether is better than writing our own solution through the runpostdeploy. I truly would like to make it as simple as possible for newbies, people who start with MVC and Yii. 

PS: No need to be sorry DaSourcerer, you are one of the 'good guys' at Yii Network... so your input and ideas are more than appreciated.

**Comment by DaSourcerer** [comment]
>  No need to be sorry DaSourcerer, you are one of the 'good guys' at Yii Network

That is very flattering. However, I feel that is hardly an excuse. I've rushed a PR that would have led to a broken project state when pulled.

**Pull request closed without merging**
